version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: cimg/node:20.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Firebase CLI
          command: npm install -g firebase-tools
      - run:
          name: Deploy to Firebase Hosting
          command: |
            echo $FIREBASE_TOKEN | firebase login:ci --token $FIREBASE_TOKEN || true
            firebase deploy --only hosting --project bean-base --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
